name: Tests

on:
  push:
    branches-ignore:
      - deploy

permissions:
  contents: read

env:
  node-dependencies-cache-name: cache-node-dependencies-1
  composer-packages-cache-name: cache-composer-packages-5
  artifacts-cache-name: cache-artifacts-5

jobs:

  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Check for cached Node dependencies
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            ./node_modules
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.node-dependencies-cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install Node dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install
          npm install cypress
      - name: Verify Cypress
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - name: Check for cached Composer packages
        id: cache-composer-packages
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.composer-packages-cache-name }}-${{ hashFiles('composer.lock') }}
      - name: Install Composer dependencies
        if: steps.cache-composer-packages.outputs.cache-hit != 'true'
        run: composer install --no-interaction --ignore-platform-reqs --optimize-autoloader

      - name: Check for cached artifacts
        id: cache-artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./public/css
            ./public/js
            ./public/mix-manifest.json
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.artifacts-cache-name }}-${{ hashFiles('resources/css/**/*.css', 'resources/js/**/*.js', 'resources/scss/**/*.scss') }}
      - name: Build artifacts
        if: steps.cache-artifacts.outputs.cache-hit != 'true'
        run: npm run prod

  unit-tests:
    needs: [ install-dependencies ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Debug
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: Setup Environment
        run: |
          cp .env.ci .env
          touch ./storage/logs/laravel.log
          touch ./database/database.sqlite

      - name: Restore Node dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.node-dependencies-cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Restore Composer packages
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.composer-packages-cache-name }}-${{ hashFiles('composer.lock') }}

      - name: Restore artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./public/css
            ./public/js
            ./public/mix-manifest.json
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.artifacts-cache-name }}-${{ hashFiles('resources/css/**/*.css', 'resources/js/**/*.js', 'resources/scss/**/*.scss') }}

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Dump Autoloader
        run: composer dump-autoload

      - name: Run Laravel Server
        run: php artisan serve &

      - name: Execute all tests via PHPUnit
        id: phpunit
        run: vendor/bin/phpunit --testsuite Unit

  feature-tests:
    needs: [ install-dependencies ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Debug
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: Setup Environment
        run: |
          cp .env.ci .env
          touch ./storage/logs/laravel.log
          touch ./database/database.sqlite

      - name: Restore Node dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.node-dependencies-cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Restore Composer packages
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.composer-packages-cache-name }}-${{ hashFiles('composer.lock') }}

      - name: Restore artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./public/css
            ./public/js
            ./public/mix-manifest.json
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.artifacts-cache-name }}-${{ hashFiles('resources/css/**/*.css', 'resources/js/**/*.js', 'resources/scss/**/*.scss') }}

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Dump Autoloader
        run: composer dump-autoload

      - name: Run Laravel Server
        run: php artisan serve &

      - name: Execute all tests via PHPUnit
        id: phpunit
        run: vendor/bin/phpunit --testsuite Feature

  dusk-tests:
    needs: [ install-dependencies ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Debug
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: Setup Environment
        run: |
          cp .env.ci .env
          touch ./storage/logs/laravel.log
          touch ./database/database.sqlite

      - name: Restore Node dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.node-dependencies-cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Restore Composer packages
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.composer-packages-cache-name }}-${{ hashFiles('composer.lock') }}

      - name: Restore artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./public/css
            ./public/js
            ./public/mix-manifest.json
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.artifacts-cache-name }}-${{ hashFiles('resources/css/**/*.css', 'resources/js/**/*.js', 'resources/scss/**/*.scss') }}

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Dump Autoloader
        run: composer dump-autoload

      - name: Update Chrome Driver
        run: |
          CHROME_VERSION="$(google-chrome --version)"
          CHROMEDRIVER_RELEASE="$(echo $CHROME_VERSION | sed 's/^Google Chrome //')"
          CHROMEDRIVER_RELEASE=${CHROMEDRIVER_RELEASE%%.*}
          php artisan dusk:chrome-driver $CHROMEDRIVER_RELEASE

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php artisan serve &

      - name: Run Laravel Dusk Tests
        id: laravel-dusk
        continue-on-error: true
        run: php artisan dusk

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: ${{ steps.laravel-dusk.outcome == 'failure' }}
        with:
          name: ${{ github.job }}-log
          path: ./storage/logs/*.log

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: ${{ steps.laravel-dusk.outcome == 'failure' }}
        with:
          name: ${{ github.job }}-screenshots
          path: ./tests/Browser/screenshots

      - name: Sanity check
        if: ${{ steps.laravel-dusk.outcome == 'failure' }}
        run: exit 2

  cypress-tests:
    needs: [ install-dependencies ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2' ]
        browser: [ 'electron', 'firefox', 'chrome', 'edge' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Debug
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: Setup Environment
        run: |
          cp .env.cypress .env
          touch ./storage/logs/laravel.log
          touch ./database/database.sqlite

      - name: Restore Node dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            ./node_modules
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.node-dependencies-cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Restore Composer packages
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.composer-packages-cache-name }}-${{ hashFiles('composer.lock') }}

      - name: Restore artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./public/css
            ./public/js
            ./public/mix-manifest.json
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-build-${{ env.artifacts-cache-name }}-${{ hashFiles('resources/css/**/*.css', 'resources/js/**/*.js', 'resources/scss/**/*.scss') }}

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Dump Autoloader
        run: composer dump-autoload

      - name: Run Cypress Tests
        id: cypress-tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: php artisan serve --quiet
          wait-on: 'http://127.0.0.1:8000'
          config: baseUrl=http://127.0.0.1:8000
          config-file: ./cypress.config.js
          record: true
          project: ./
          browser: ${{ matrix.browser }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ github.job }}-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ github.job }}-videos
          path: cypress/videos

  deploy:
    needs: [ unit-tests, feature-tests, dusk-tests, cypress-tests ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger deployment of main branch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: Deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
